//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.11 at 08:37:52 PM CET 
//


package com.basf.xpview.model.io.xmplant;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * A BsplineSurface is general form of Rational or polynomial surface represented by control points, basis fuinctions and possibly weights.
 * 
 * <p>Java class for BsplineSurface complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BsplineSurface">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{}Presentation" minOccurs="0"/>
 *         &lt;element ref="{}Extent"/>
 *         &lt;element name="ControlPointArray" type="{}ControlPointArray"/>
 *         &lt;element name="KnotMultiplicitiesU" type="{}KnotMultiplicities" minOccurs="0"/>
 *         &lt;element name="KnotMultiplicitiesV" type="{}KnotMultiplicities" minOccurs="0"/>
 *         &lt;element name="KnotsU" type="{}Knots" minOccurs="0"/>
 *         &lt;element name="KnotsV" type="{}Knots" minOccurs="0"/>
 *         &lt;element name="Weights" type="{}Weights" minOccurs="0"/>
 *         &lt;element ref="{}GenericAttributes" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="DegreeU" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="DegreeV" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="SurfaceType" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="BsplineSurface"/>
 *             &lt;enumeration value="BsplineSurfaceWithKnots"/>
 *             &lt;enumeration value="RationalBsplineSurface"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="SurfaceForm">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="Plane"/>
 *             &lt;enumeration value="Cylindrical"/>
 *             &lt;enumeration value="Conical"/>
 *             &lt;enumeration value="Spherical"/>
 *             &lt;enumeration value="Toroidal"/>
 *             &lt;enumeration value="SurfaceOfRevolution"/>
 *             &lt;enumeration value="RuledSurface"/>
 *             &lt;enumeration value="GeneralisedCone"/>
 *             &lt;enumeration value="Quadratic"/>
 *             &lt;enumeration value="SurfaceOfLinearExtrusion"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="NumControlPointsU" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="NumControlPointsV" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="NumKnotsU" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="NumKnotsV" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ClosedU" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ClosedV" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="SelfIntersect" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BsplineSurface", propOrder = {
    "presentationOrExtentOrControlPointArray"
})
public class BsplineSurface {

    @XmlElementRefs({
        @XmlElementRef(name = "KnotMultiplicitiesV", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "GenericAttributes", type = GenericAttributes.class, required = false),
        @XmlElementRef(name = "KnotsV", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "KnotMultiplicitiesU", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ControlPointArray", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Weights", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Extent", type = Extent.class, required = false),
        @XmlElementRef(name = "KnotsU", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Presentation", type = Presentation.class, required = false)
    })
    protected List<Object> presentationOrExtentOrControlPointArray;
    @XmlAttribute(name = "DegreeU", required = true)
    protected BigInteger degreeU;
    @XmlAttribute(name = "DegreeV", required = true)
    protected BigInteger degreeV;
    @XmlAttribute(name = "SurfaceType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected java.lang.String surfaceType;
    @XmlAttribute(name = "SurfaceForm")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected java.lang.String surfaceForm;
    @XmlAttribute(name = "NumControlPointsU", required = true)
    protected BigInteger numControlPointsU;
    @XmlAttribute(name = "NumControlPointsV", required = true)
    protected BigInteger numControlPointsV;
    @XmlAttribute(name = "NumKnotsU")
    protected BigInteger numKnotsU;
    @XmlAttribute(name = "NumKnotsV")
    protected BigInteger numKnotsV;
    @XmlAttribute(name = "ClosedU")
    protected Boolean closedU;
    @XmlAttribute(name = "ClosedV")
    protected Boolean closedV;
    @XmlAttribute(name = "SelfIntersect")
    protected Boolean selfIntersect;

    /**
     * Gets the value of the presentationOrExtentOrControlPointArray property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the presentationOrExtentOrControlPointArray property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPresentationOrExtentOrControlPointArray().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link KnotMultiplicities }{@code >}
     * {@link GenericAttributes }
     * {@link JAXBElement }{@code <}{@link Knots }{@code >}
     * {@link JAXBElement }{@code <}{@link ControlPointArray }{@code >}
     * {@link JAXBElement }{@code <}{@link KnotMultiplicities }{@code >}
     * {@link JAXBElement }{@code <}{@link Weights }{@code >}
     * {@link Extent }
     * {@link JAXBElement }{@code <}{@link Knots }{@code >}
     * {@link Presentation }
     * 
     * 
     */
    public List<Object> getPresentationOrExtentOrControlPointArray() {
        if (presentationOrExtentOrControlPointArray == null) {
            presentationOrExtentOrControlPointArray = new ArrayList<Object>();
        }
        return this.presentationOrExtentOrControlPointArray;
    }

    /**
     * Gets the value of the degreeU property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDegreeU() {
        return degreeU;
    }

    /**
     * Sets the value of the degreeU property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDegreeU(BigInteger value) {
        this.degreeU = value;
    }

    /**
     * Gets the value of the degreeV property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDegreeV() {
        return degreeV;
    }

    /**
     * Sets the value of the degreeV property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDegreeV(BigInteger value) {
        this.degreeV = value;
    }

    /**
     * Gets the value of the surfaceType property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getSurfaceType() {
        return surfaceType;
    }

    /**
     * Sets the value of the surfaceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setSurfaceType(java.lang.String value) {
        this.surfaceType = value;
    }

    /**
     * Gets the value of the surfaceForm property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getSurfaceForm() {
        return surfaceForm;
    }

    /**
     * Sets the value of the surfaceForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setSurfaceForm(java.lang.String value) {
        this.surfaceForm = value;
    }

    /**
     * Gets the value of the numControlPointsU property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumControlPointsU() {
        return numControlPointsU;
    }

    /**
     * Sets the value of the numControlPointsU property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumControlPointsU(BigInteger value) {
        this.numControlPointsU = value;
    }

    /**
     * Gets the value of the numControlPointsV property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumControlPointsV() {
        return numControlPointsV;
    }

    /**
     * Sets the value of the numControlPointsV property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumControlPointsV(BigInteger value) {
        this.numControlPointsV = value;
    }

    /**
     * Gets the value of the numKnotsU property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumKnotsU() {
        return numKnotsU;
    }

    /**
     * Sets the value of the numKnotsU property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumKnotsU(BigInteger value) {
        this.numKnotsU = value;
    }

    /**
     * Gets the value of the numKnotsV property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumKnotsV() {
        return numKnotsV;
    }

    /**
     * Sets the value of the numKnotsV property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumKnotsV(BigInteger value) {
        this.numKnotsV = value;
    }

    /**
     * Gets the value of the closedU property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isClosedU() {
        return closedU;
    }

    /**
     * Sets the value of the closedU property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setClosedU(Boolean value) {
        this.closedU = value;
    }

    /**
     * Gets the value of the closedV property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isClosedV() {
        return closedV;
    }

    /**
     * Sets the value of the closedV property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setClosedV(Boolean value) {
        this.closedV = value;
    }

    /**
     * Gets the value of the selfIntersect property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSelfIntersect() {
        return selfIntersect;
    }

    /**
     * Sets the value of the selfIntersect property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSelfIntersect(Boolean value) {
        this.selfIntersect = value;
    }

}
