//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.11 at 08:37:52 PM CET 
//


package com.basf.xpview.model.io.xmplant;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * A BsplineCurve is general form of Rational or polynomial curve represented by control points, basis fuinctions and possibly weights.
 * 
 * <p>Java class for BsplineCurve complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BsplineCurve">
 *   &lt;complexContent>
 *     &lt;extension base="{}Curve">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{}Presentation" minOccurs="0"/>
 *         &lt;element ref="{}Extent"/>
 *         &lt;element name="ControlPoints" type="{}ControlPoints"/>
 *         &lt;element name="KnotMultiplicities" type="{}KnotMultiplicities" minOccurs="0"/>
 *         &lt;element name="Knots" type="{}Knots" minOccurs="0"/>
 *         &lt;element name="WeightsData" type="{}WeightsData" minOccurs="0"/>
 *         &lt;element ref="{}GenericAttributes" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="Degree" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="CurveType" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="BsplineCurve"/>
 *             &lt;enumeration value="BsplineCurveWithKnots"/>
 *             &lt;enumeration value="RationalBsplineCurve"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CurveForm">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="PolyLine"/>
 *             &lt;enumeration value="CircularArc"/>
 *             &lt;enumeration value="EllipticArc"/>
 *             &lt;enumeration value="ParabolicArc"/>
 *             &lt;enumeration value="HyperbolicArc"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="NumControlPoints" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="NumKnots" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="Closed" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="SelfIntersect" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BsplineCurve", propOrder = {
    "presentationOrExtentOrControlPoints"
})
public class BsplineCurve
    extends Curve
{

    @XmlElements({
        @XmlElement(name = "Presentation", type = Presentation.class),
        @XmlElement(name = "Extent", type = Extent.class),
        @XmlElement(name = "ControlPoints", type = ControlPoints.class),
        @XmlElement(name = "KnotMultiplicities", type = KnotMultiplicities.class),
        @XmlElement(name = "Knots", type = Knots.class),
        @XmlElement(name = "WeightsData", type = WeightsData.class),
        @XmlElement(name = "GenericAttributes", type = GenericAttributes.class)
    })
    protected List<Object> presentationOrExtentOrControlPoints;
    @XmlAttribute(name = "Degree", required = true)
    protected BigInteger degree;
    @XmlAttribute(name = "CurveType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected java.lang.String curveType;
    @XmlAttribute(name = "CurveForm")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected java.lang.String curveForm;
    @XmlAttribute(name = "NumControlPoints", required = true)
    protected BigInteger numControlPoints;
    @XmlAttribute(name = "NumKnots")
    protected BigInteger numKnots;
    @XmlAttribute(name = "Closed")
    protected Boolean closed;
    @XmlAttribute(name = "SelfIntersect")
    protected Boolean selfIntersect;

    /**
     * Gets the value of the presentationOrExtentOrControlPoints property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the presentationOrExtentOrControlPoints property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPresentationOrExtentOrControlPoints().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Presentation }
     * {@link Extent }
     * {@link ControlPoints }
     * {@link KnotMultiplicities }
     * {@link Knots }
     * {@link WeightsData }
     * {@link GenericAttributes }
     * 
     * 
     */
    public List<Object> getPresentationOrExtentOrControlPoints() {
        if (presentationOrExtentOrControlPoints == null) {
            presentationOrExtentOrControlPoints = new ArrayList<Object>();
        }
        return this.presentationOrExtentOrControlPoints;
    }

    /**
     * Gets the value of the degree property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDegree() {
        return degree;
    }

    /**
     * Sets the value of the degree property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDegree(BigInteger value) {
        this.degree = value;
    }

    /**
     * Gets the value of the curveType property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getCurveType() {
        return curveType;
    }

    /**
     * Sets the value of the curveType property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setCurveType(java.lang.String value) {
        this.curveType = value;
    }

    /**
     * Gets the value of the curveForm property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getCurveForm() {
        return curveForm;
    }

    /**
     * Sets the value of the curveForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setCurveForm(java.lang.String value) {
        this.curveForm = value;
    }

    /**
     * Gets the value of the numControlPoints property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumControlPoints() {
        return numControlPoints;
    }

    /**
     * Sets the value of the numControlPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumControlPoints(BigInteger value) {
        this.numControlPoints = value;
    }

    /**
     * Gets the value of the numKnots property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumKnots() {
        return numKnots;
    }

    /**
     * Sets the value of the numKnots property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumKnots(BigInteger value) {
        this.numKnots = value;
    }

    /**
     * Gets the value of the closed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isClosed() {
        return closed;
    }

    /**
     * Sets the value of the closed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setClosed(Boolean value) {
        this.closed = value;
    }

    /**
     * Gets the value of the selfIntersect property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSelfIntersect() {
        return selfIntersect;
    }

    /**
     * Sets the value of the selfIntersect property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSelfIntersect(Boolean value) {
        this.selfIntersect = value;
    }

}
