//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.11 at 08:37:52 PM CET 
//


package com.basf.xpview.model.io.xmplant;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}PlantItem">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}Connection" minOccurs="0"/>
 *         &lt;element ref="{}CenterLine"/>
 *         &lt;element ref="{}Component"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "connectionOrCenterLineOrComponent"
})
@XmlRootElement(name = "SignalLine")
public class SignalLine
    extends PlantItem
{

    @XmlElements({
        @XmlElement(name = "Connection", type = Connection.class),
        @XmlElement(name = "CenterLine", type = CenterLine.class),
        @XmlElement(name = "Component", type = Component.class)
    })
    protected List<Object> connectionOrCenterLineOrComponent;

    /**
     * Gets the value of the connectionOrCenterLineOrComponent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the connectionOrCenterLineOrComponent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConnectionOrCenterLineOrComponent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Connection }
     * {@link CenterLine }
     * {@link Component }
     * 
     * 
     */
    public List<Object> getConnectionOrCenterLineOrComponent() {
        if (connectionOrCenterLineOrComponent == null) {
            connectionOrCenterLineOrComponent = new ArrayList<Object>();
        }
        return this.connectionOrCenterLineOrComponent;
    }

}
