//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.11 at 08:37:52 PM CET 
//


package org.dexpi.xpview.model.io.xmplant;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AreaUnitsType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AreaUnitsType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="sq mm"/>
 *     &lt;enumeration value="sq cm"/>
 *     &lt;enumeration value="sq m"/>
 *     &lt;enumeration value="sq km"/>
 *     &lt;enumeration value="SquareMillimetre"/>
 *     &lt;enumeration value="SquareCentimetre"/>
 *     &lt;enumeration value="SquareMetre"/>
 *     &lt;enumeration value="SquareKilometre"/>
 *     &lt;enumeration value="SquareInch"/>
 *     &lt;enumeration value="SquareFoot"/>
 *     &lt;enumeration value="SquareYard"/>
 *     &lt;enumeration value="SquareMile"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AreaUnitsType")
@XmlEnum
public enum AreaUnitsType {

    @XmlEnumValue("sq mm")
    SQ_MM("sq mm"),
    @XmlEnumValue("sq cm")
    SQ_CM("sq cm"),
    @XmlEnumValue("sq m")
    SQ_M("sq m"),
    @XmlEnumValue("sq km")
    SQ_KM("sq km"),
    @XmlEnumValue("SquareMillimetre")
    SQUARE_MILLIMETRE("SquareMillimetre"),
    @XmlEnumValue("SquareCentimetre")
    SQUARE_CENTIMETRE("SquareCentimetre"),
    @XmlEnumValue("SquareMetre")
    SQUARE_METRE("SquareMetre"),
    @XmlEnumValue("SquareKilometre")
    SQUARE_KILOMETRE("SquareKilometre"),
    @XmlEnumValue("SquareInch")
    SQUARE_INCH("SquareInch"),
    @XmlEnumValue("SquareFoot")
    SQUARE_FOOT("SquareFoot"),
    @XmlEnumValue("SquareYard")
    SQUARE_YARD("SquareYard"),
    @XmlEnumValue("SquareMile")
    SQUARE_MILE("SquareMile");
    private final java.lang.String value;

    AreaUnitsType(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static AreaUnitsType fromValue(java.lang.String v) {
        for (AreaUnitsType c: AreaUnitsType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
