//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.11 at 08:37:52 PM CET 
//


package org.dexpi.xpview.model.io.xmplant;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="LinkedPersistentID" type="{}PersistentID" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="DrawingName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="LinkLabel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "linkedPersistentID"
})
@XmlRootElement(name = "CrossPageConnection")
public class CrossPageConnection {

    @XmlElement(name = "LinkedPersistentID")
    protected PersistentID linkedPersistentID;
    @XmlAttribute(name = "DrawingName")
    protected java.lang.String drawingName;
    @XmlAttribute(name = "LinkLabel")
    protected java.lang.String linkLabel;

    /**
     * Gets the value of the linkedPersistentID property.
     * 
     * @return
     *     possible object is
     *     {@link PersistentID }
     *     
     */
    public PersistentID getLinkedPersistentID() {
        return linkedPersistentID;
    }

    /**
     * Sets the value of the linkedPersistentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersistentID }
     *     
     */
    public void setLinkedPersistentID(PersistentID value) {
        this.linkedPersistentID = value;
    }

    /**
     * Gets the value of the drawingName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getDrawingName() {
        return drawingName;
    }

    /**
     * Sets the value of the drawingName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setDrawingName(java.lang.String value) {
        this.drawingName = value;
    }

    /**
     * Gets the value of the linkLabel property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getLinkLabel() {
        return linkLabel;
    }

    /**
     * Sets the value of the linkLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setLinkLabel(java.lang.String value) {
        this.linkLabel = value;
    }

}
