//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.11 at 08:37:52 PM CET 
//


package com.basf.xpview.model.io.xmplant;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DistanceUnitsType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DistanceUnitsType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="Micron"/>
 *     &lt;enumeration value="Millimetre"/>
 *     &lt;enumeration value="Centimetre"/>
 *     &lt;enumeration value="Decimetre"/>
 *     &lt;enumeration value="Metre"/>
 *     &lt;enumeration value="Kilometre"/>
 *     &lt;enumeration value="Inch"/>
 *     &lt;enumeration value="Foot"/>
 *     &lt;enumeration value="Yard"/>
 *     &lt;enumeration value="Mile"/>
 *     &lt;enumeration value="mm"/>
 *     &lt;enumeration value="cm"/>
 *     &lt;enumeration value="m"/>
 *     &lt;enumeration value="km"/>
 *     &lt;enumeration value="in"/>
 *     &lt;enumeration value="ft"/>
 *     &lt;enumeration value="yd"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DistanceUnitsType")
@XmlEnum
public enum DistanceUnitsType {

    @XmlEnumValue("Micron")
    MICRON("Micron"),
    @XmlEnumValue("Millimetre")
    MILLIMETRE("Millimetre"),
    @XmlEnumValue("Centimetre")
    CENTIMETRE("Centimetre"),
    @XmlEnumValue("Decimetre")
    DECIMETRE("Decimetre"),
    @XmlEnumValue("Metre")
    METRE("Metre"),
    @XmlEnumValue("Kilometre")
    KILOMETRE("Kilometre"),
    @XmlEnumValue("Inch")
    INCH("Inch"),
    @XmlEnumValue("Foot")
    FOOT("Foot"),
    @XmlEnumValue("Yard")
    YARD("Yard"),
    @XmlEnumValue("Mile")
    MILE("Mile"),
    @XmlEnumValue("mm")
    MM("mm"),
    @XmlEnumValue("cm")
    CM("cm"),
    @XmlEnumValue("m")
    M("m"),
    @XmlEnumValue("km")
    KM("km"),
    @XmlEnumValue("in")
    IN("in"),
    @XmlEnumValue("ft")
    FT("ft"),
    @XmlEnumValue("yd")
    YD("yd");
    private final java.lang.String value;

    DistanceUnitsType(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static DistanceUnitsType fromValue(java.lang.String v) {
        for (DistanceUnitsType c: DistanceUnitsType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
