//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.11 at 08:37:52 PM CET 
//


package org.dexpi.xpview.model.io.xmplant;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{}Position"/>
 *         &lt;element ref="{}NominalDiameter" minOccurs="0"/>
 *         &lt;element ref="{}EndPreparation" minOccurs="0"/>
 *         &lt;element ref="{}GasketGap" minOccurs="0"/>
 *         &lt;element ref="{}Rating" minOccurs="0"/>
 *         &lt;element ref="{}ScheduleThickness" minOccurs="0"/>
 *         &lt;element ref="{}WeldType" minOccurs="0"/>
 *         &lt;element ref="{}GenericAttributes" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Type">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="unspecified"/>
 *             &lt;enumeration value="process"/>
 *             &lt;enumeration value="signal"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Function">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="unspecified"/>
 *             &lt;enumeration value="primary"/>
 *             &lt;enumeration value="secondary"/>
 *             &lt;enumeration value="tap"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Flow">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="unspecified"/>
 *             &lt;enumeration value="in"/>
 *             &lt;enumeration value="out"/>
 *             &lt;enumeration value="both"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "positionOrNominalDiameterOrEndPreparation"
})
@XmlRootElement(name = "Node")
public class Node {

    @XmlElementRefs({
        @XmlElementRef(name = "GasketGap", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "GenericAttributes", type = GenericAttributes.class, required = false),
        @XmlElementRef(name = "NominalDiameter", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Rating", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Position", type = Position.class, required = false),
        @XmlElementRef(name = "ScheduleThickness", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "EndPreparation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "WeldType", type = JAXBElement.class, required = false)
    })
    protected List<Object> positionOrNominalDiameterOrEndPreparation;
    @XmlAttribute(name = "Name")
    protected java.lang.String name;
    @XmlAttribute(name = "Type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected java.lang.String type;
    @XmlAttribute(name = "Function")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected java.lang.String function;
    @XmlAttribute(name = "Flow")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected java.lang.String flow;

    /**
     * Gets the value of the positionOrNominalDiameterOrEndPreparation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the positionOrNominalDiameterOrEndPreparation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPositionOrNominalDiameterOrEndPreparation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link DistanceDouble }{@code >}
     * {@link GenericAttributes }
     * {@link JAXBElement }{@code <}{@link DistanceDouble }{@code >}
     * {@link JAXBElement }{@code <}{@link org.dexpi.xpview.model.io.xmplant.String }{@code >}
     * {@link Position }
     * {@link JAXBElement }{@code <}{@link org.dexpi.xpview.model.io.xmplant.String }{@code >}
     * {@link JAXBElement }{@code <}{@link DistanceString }{@code >}
     * {@link JAXBElement }{@code <}{@link org.dexpi.xpview.model.io.xmplant.String }{@code >}
     * 
     * 
     */
    public List<Object> getPositionOrNominalDiameterOrEndPreparation() {
        if (positionOrNominalDiameterOrEndPreparation == null) {
            positionOrNominalDiameterOrEndPreparation = new ArrayList<Object>();
        }
        return this.positionOrNominalDiameterOrEndPreparation;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setName(java.lang.String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setType(java.lang.String value) {
        this.type = value;
    }

    /**
     * Gets the value of the function property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getFunction() {
        return function;
    }

    /**
     * Sets the value of the function property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setFunction(java.lang.String value) {
        this.function = value;
    }

    /**
     * Gets the value of the flow property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getFlow() {
        return flow;
    }

    /**
     * Sets the value of the flow property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setFlow(java.lang.String value) {
        this.flow = value;
    }

}
