//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.11 at 08:37:52 PM CET 
//


package org.dexpi.xpview.model.io.xmplant;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}PlantItem">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}NozzleType"/>
 *         &lt;element ref="{}NominalDiameter" minOccurs="0"/>
 *         &lt;element ref="{}Height" minOccurs="0"/>
 *         &lt;element ref="{}Rating" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nozzleTypeOrNominalDiameterOrHeight"
})
@XmlRootElement(name = "Nozzle")
public class Nozzle
    extends PlantItem
{

    @XmlElementRefs({
        @XmlElementRef(name = "Height", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "NominalDiameter", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Rating", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "NozzleType", type = NozzleType.class, required = false)
    })
    protected List<Object> nozzleTypeOrNominalDiameterOrHeight;

    /**
     * Gets the value of the nozzleTypeOrNominalDiameterOrHeight property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nozzleTypeOrNominalDiameterOrHeight property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNozzleTypeOrNominalDiameterOrHeight().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NozzleType }
     * {@link JAXBElement }{@code <}{@link DistanceDouble }{@code >}
     * {@link JAXBElement }{@code <}{@link DistanceDouble }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Object> getNozzleTypeOrNominalDiameterOrHeight() {
        if (nozzleTypeOrNominalDiameterOrHeight == null) {
            nozzleTypeOrNominalDiameterOrHeight = new ArrayList<Object>();
        }
        return this.nozzleTypeOrNominalDiameterOrHeight;
    }

}
