//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.11 at 08:37:52 PM CET 
//


package org.dexpi.xpview.model.io.xmplant;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}AnnotationItem">
 *       &lt;sequence>
 *         &lt;element ref="{}CrossPageConnection" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "crossPageConnection"
})
@XmlRootElement(name = "PipeConnectorSymbol")
public class PipeConnectorSymbol
    extends AnnotationItem
{

    @XmlElement(name = "CrossPageConnection")
    protected CrossPageConnection crossPageConnection;

    /**
     * Gets the value of the crossPageConnection property.
     * 
     * @return
     *     possible object is
     *     {@link CrossPageConnection }
     *     
     */
    public CrossPageConnection getCrossPageConnection() {
        return crossPageConnection;
    }

    /**
     * Sets the value of the crossPageConnection property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrossPageConnection }
     *     
     */
    public void setCrossPageConnection(CrossPageConnection value) {
        this.crossPageConnection = value;
    }

}
