//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.11 at 08:37:52 PM CET 
//


package com.basf.xpview.model.io.xmplant;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for PlantItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PlantItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}Presentation" minOccurs="0"/>
 *         &lt;element ref="{}Extent"/>
 *         &lt;element ref="{}PersistentID"/>
 *         &lt;element ref="{}Position"/>
 *         &lt;element ref="{}Scale"/>
 *         &lt;element ref="{}Surface"/>
 *         &lt;element ref="{}Curve" maxOccurs="unbounded"/>
 *         &lt;element ref="{}ConnectionPoints"/>
 *         &lt;element ref="{}PConnectionPoints"/>
 *         &lt;element ref="{}Text"/>
 *         &lt;element ref="{}Identifier"/>
 *         &lt;element ref="{}Description"/>
 *         &lt;element ref="{}Weight"/>
 *         &lt;element ref="{}Material"/>
 *         &lt;element ref="{}MaterialDescription"/>
 *         &lt;element name="ModelNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Supplier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Manufacturer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}GenericAttributes" maxOccurs="unbounded"/>
 *         &lt;element ref="{}Association" maxOccurs="unbounded"/>
 *         &lt;element ref="{}History"/>
 *       &lt;/choice>
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="TagName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Specification" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="StockNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ComponentClass" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ComponentName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ComponentType">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="Normal"/>
 *             &lt;enumeration value="Explicit"/>
 *             &lt;enumeration value="Parametric"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Revision" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Status">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="Current"/>
 *             &lt;enumeration value="Deleted"/>
 *             &lt;enumeration value="Modified"/>
 *             &lt;enumeration value="New"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlantItem", propOrder = {
    "presentationOrExtentOrPersistentID"
})
@XmlSeeAlso({
    JunctionBox.class,
    PipingComponent.class,
    Terminal.class,
    TerminalStrip.class,
    InstrumentConnection.class,
    PipingNetworkSegment.class,
    PipingNetworkSystem.class,
    SignalLine.class,
    InstrumentLoop.class,
    PlantArea.class,
    InstrumentComponent.class,
    ProcessInstrument.class,
    Component.class,
    Nozzle.class,
    Equipment.class
})
public class PlantItem {

    @XmlElementRefs({
        @XmlElementRef(name = "Text", type = Text.class, required = false),
        @XmlElementRef(name = "PConnectionPoints", type = PConnectionPoints.class, required = false),
        @XmlElementRef(name = "Material", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Curve", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Extent", type = Extent.class, required = false),
        @XmlElementRef(name = "Identifier", type = Identifier.class, required = false),
        @XmlElementRef(name = "Weight", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "History", type = History.class, required = false),
        @XmlElementRef(name = "Presentation", type = Presentation.class, required = false),
        @XmlElementRef(name = "Surface", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ConnectionPoints", type = ConnectionPoints.class, required = false),
        @XmlElementRef(name = "GenericAttributes", type = GenericAttributes.class, required = false),
        @XmlElementRef(name = "PersistentID", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Description", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Manufacturer", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Position", type = Position.class, required = false),
        @XmlElementRef(name = "Scale", type = Scale.class, required = false),
        @XmlElementRef(name = "ModelNumber", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Supplier", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Association", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "MaterialDescription", type = JAXBElement.class, required = false)
    })
    protected List<Object> presentationOrExtentOrPersistentID;
    @XmlAttribute(name = "ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String id;
    @XmlAttribute(name = "TagName")
    protected java.lang.String tagName;
    @XmlAttribute(name = "Specification")
    protected java.lang.String specification;
    @XmlAttribute(name = "StockNumber")
    protected java.lang.String stockNumber;
    @XmlAttribute(name = "ComponentClass")
    protected java.lang.String componentClass;
    @XmlAttribute(name = "ComponentName")
    protected java.lang.String componentName;
    @XmlAttribute(name = "ComponentType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected java.lang.String componentType;
    @XmlAttribute(name = "Revision")
    protected java.lang.String revision;
    @XmlAttribute(name = "Status")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected java.lang.String status;

    /**
     * Gets the value of the presentationOrExtentOrPersistentID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the presentationOrExtentOrPersistentID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPresentationOrExtentOrPersistentID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Line }{@code >}
     * {@link Extent }
     * {@link JAXBElement }{@code <}{@link Shape }{@code >}
     * {@link Identifier }
     * {@link JAXBElement }{@code <}{@link WeightDouble }{@code >}
     * {@link Presentation }
     * {@link JAXBElement }{@code <}{@link TrimmedCurve }{@code >}
     * {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}
     * {@link Position }
     * {@link JAXBElement }{@code <}{@link CompositeCurve }{@code >}
     * {@link Scale }
     * {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}
     * {@link JAXBElement }{@code <}{@link Association }{@code >}
     * {@link Text }
     * {@link PConnectionPoints }
     * {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}
     * {@link JAXBElement }{@code <}{@link Curve }{@code >}
     * {@link JAXBElement }{@code <}{@link PolyLine }{@code >}
     * {@link JAXBElement }{@code <}{@link Circle }{@code >}
     * {@link History }
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link ConnectionPoints }
     * {@link GenericAttributes }
     * {@link JAXBElement }{@code <}{@link PersistentID }{@code >}
     * {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}
     * {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}
     * {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}
     * {@link JAXBElement }{@code <}{@link BsplineCurve }{@code >}
     * {@link JAXBElement }{@code <}{@link BsplineSurface }{@code >}
     * {@link JAXBElement }{@code <}{@link CurveBoundedSurface }{@code >}
     * {@link JAXBElement }{@code <}{@link Ellipse }{@code >}
     * 
     * 
     */
    public List<Object> getPresentationOrExtentOrPersistentID() {
        if (presentationOrExtentOrPersistentID == null) {
            presentationOrExtentOrPersistentID = new ArrayList<Object>();
        }
        return this.presentationOrExtentOrPersistentID;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setID(java.lang.String value) {
        this.id = value;
    }

    /**
     * Gets the value of the tagName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getTagName() {
        return tagName;
    }

    /**
     * Sets the value of the tagName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setTagName(java.lang.String value) {
        this.tagName = value;
    }

    /**
     * Gets the value of the specification property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getSpecification() {
        return specification;
    }

    /**
     * Sets the value of the specification property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setSpecification(java.lang.String value) {
        this.specification = value;
    }

    /**
     * Gets the value of the stockNumber property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getStockNumber() {
        return stockNumber;
    }

    /**
     * Sets the value of the stockNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setStockNumber(java.lang.String value) {
        this.stockNumber = value;
    }

    /**
     * Gets the value of the componentClass property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getComponentClass() {
        return componentClass;
    }

    /**
     * Sets the value of the componentClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setComponentClass(java.lang.String value) {
        this.componentClass = value;
    }

    /**
     * Gets the value of the componentName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getComponentName() {
        return componentName;
    }

    /**
     * Sets the value of the componentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setComponentName(java.lang.String value) {
        this.componentName = value;
    }

    /**
     * Gets the value of the componentType property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getComponentType() {
        return componentType;
    }

    /**
     * Sets the value of the componentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setComponentType(java.lang.String value) {
        this.componentType = value;
    }

    /**
     * Gets the value of the revision property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getRevision() {
        return revision;
    }

    /**
     * Sets the value of the revision property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setRevision(java.lang.String value) {
        this.revision = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setStatus(java.lang.String value) {
        this.status = value;
    }

}
