//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.11 at 08:37:52 PM CET 
//


package com.basf.xpview.model.io.xmplant;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PlantInformation"/>
 *         &lt;element ref="{}Extent"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{}Presentation"/>
 *           &lt;element ref="{}ShapeCatalogue"/>
 *           &lt;element ref="{}Drawing"/>
 *           &lt;element ref="{}PlantArea"/>
 *           &lt;element ref="{}Equipment"/>
 *           &lt;element ref="{}InstrumentComponent"/>
 *           &lt;element ref="{}InstrumentLoop"/>
 *           &lt;element ref="{}SignalLine"/>
 *           &lt;element ref="{}SignalConnectorSymbol"/>
 *           &lt;element ref="{}PipingNetworkSystem"/>
 *           &lt;element ref="{}ProcessInstrument"/>
 *           &lt;element ref="{}Curve"/>
 *           &lt;element ref="{}Text"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "plantInformation",
    "extent",
    "presentationOrShapeCatalogueOrDrawing"
})
@XmlRootElement(name = "PlantModel")
public class PlantModel {

    @XmlElement(name = "PlantInformation", required = true)
    protected PlantInformation plantInformation;
    @XmlElement(name = "Extent", required = true)
    protected Extent extent;
    @XmlElementRefs({
        @XmlElementRef(name = "Text", type = Text.class, required = false),
        @XmlElementRef(name = "ProcessInstrument", type = ProcessInstrument.class, required = false),
        @XmlElementRef(name = "SignalConnectorSymbol", type = SignalConnectorSymbol.class, required = false),
        @XmlElementRef(name = "Curve", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Equipment", type = Equipment.class, required = false),
        @XmlElementRef(name = "SignalLine", type = SignalLine.class, required = false),
        @XmlElementRef(name = "InstrumentComponent", type = InstrumentComponent.class, required = false),
        @XmlElementRef(name = "PlantArea", type = PlantArea.class, required = false),
        @XmlElementRef(name = "Drawing", type = Drawing.class, required = false),
        @XmlElementRef(name = "ShapeCatalogue", type = ShapeCatalogue.class, required = false),
        @XmlElementRef(name = "InstrumentLoop", type = InstrumentLoop.class, required = false),
        @XmlElementRef(name = "Presentation", type = Presentation.class, required = false),
        @XmlElementRef(name = "PipingNetworkSystem", type = PipingNetworkSystem.class, required = false)
    })
    protected List<Object> presentationOrShapeCatalogueOrDrawing;

    /**
     * Gets the value of the plantInformation property.
     * 
     * @return
     *     possible object is
     *     {@link PlantInformation }
     *     
     */
    public PlantInformation getPlantInformation() {
        return plantInformation;
    }

    /**
     * Sets the value of the plantInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlantInformation }
     *     
     */
    public void setPlantInformation(PlantInformation value) {
        this.plantInformation = value;
    }

    /**
     * Gets the value of the extent property.
     * 
     * @return
     *     possible object is
     *     {@link Extent }
     *     
     */
    public Extent getExtent() {
        return extent;
    }

    /**
     * Sets the value of the extent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Extent }
     *     
     */
    public void setExtent(Extent value) {
        this.extent = value;
    }

    /**
     * Gets the value of the presentationOrShapeCatalogueOrDrawing property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the presentationOrShapeCatalogueOrDrawing property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPresentationOrShapeCatalogueOrDrawing().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Text }
     * {@link JAXBElement }{@code <}{@link Line }{@code >}
     * {@link Equipment }
     * {@link JAXBElement }{@code <}{@link Curve }{@code >}
     * {@link SignalLine }
     * {@link JAXBElement }{@code <}{@link PolyLine }{@code >}
     * {@link JAXBElement }{@code <}{@link Circle }{@code >}
     * {@link PlantArea }
     * {@link JAXBElement }{@code <}{@link Shape }{@code >}
     * {@link ShapeCatalogue }
     * {@link Presentation }
     * {@link InstrumentLoop }
     * {@link ProcessInstrument }
     * {@link SignalConnectorSymbol }
     * {@link JAXBElement }{@code <}{@link TrimmedCurve }{@code >}
     * {@link JAXBElement }{@code <}{@link CompositeCurve }{@code >}
     * {@link InstrumentComponent }
     * {@link JAXBElement }{@code <}{@link BsplineCurve }{@code >}
     * {@link Drawing }
     * {@link PipingNetworkSystem }
     * {@link JAXBElement }{@code <}{@link Ellipse }{@code >}
     * 
     * 
     */
    public List<Object> getPresentationOrShapeCatalogueOrDrawing() {
        if (presentationOrShapeCatalogueOrDrawing == null) {
            presentationOrShapeCatalogueOrDrawing = new ArrayList<Object>();
        }
        return this.presentationOrShapeCatalogueOrDrawing;
    }

}
