//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.11 at 08:37:52 PM CET 
//


package com.basf.xpview.model.io.xmplant;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PressureUnitsType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PressureUnitsType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="Picopascal"/>
 *     &lt;enumeration value="Micropascal"/>
 *     &lt;enumeration value="Millipascal"/>
 *     &lt;enumeration value="Pascal"/>
 *     &lt;enumeration value="Kilopascal"/>
 *     &lt;enumeration value="Megapascal"/>
 *     &lt;enumeration value="Gigapascal"/>
 *     &lt;enumeration value="MillinewtonMetreSquared"/>
 *     &lt;enumeration value="NewtonMetreSquared"/>
 *     &lt;enumeration value="KilonewtonMetreSquared"/>
 *     &lt;enumeration value="Bara"/>
 *     &lt;enumeration value="Barg"/>
 *     &lt;enumeration value="Bar"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PressureUnitsType")
@XmlEnum
public enum PressureUnitsType {

    @XmlEnumValue("Picopascal")
    PICOPASCAL("Picopascal"),
    @XmlEnumValue("Micropascal")
    MICROPASCAL("Micropascal"),
    @XmlEnumValue("Millipascal")
    MILLIPASCAL("Millipascal"),
    @XmlEnumValue("Pascal")
    PASCAL("Pascal"),
    @XmlEnumValue("Kilopascal")
    KILOPASCAL("Kilopascal"),
    @XmlEnumValue("Megapascal")
    MEGAPASCAL("Megapascal"),
    @XmlEnumValue("Gigapascal")
    GIGAPASCAL("Gigapascal"),
    @XmlEnumValue("MillinewtonMetreSquared")
    MILLINEWTON_METRE_SQUARED("MillinewtonMetreSquared"),
    @XmlEnumValue("NewtonMetreSquared")
    NEWTON_METRE_SQUARED("NewtonMetreSquared"),
    @XmlEnumValue("KilonewtonMetreSquared")
    KILONEWTON_METRE_SQUARED("KilonewtonMetreSquared"),
    @XmlEnumValue("Bara")
    BARA("Bara"),
    @XmlEnumValue("Barg")
    BARG("Barg"),
    @XmlEnumValue("Bar")
    BAR("Bar");
    private final java.lang.String value;

    PressureUnitsType(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static PressureUnitsType fromValue(java.lang.String v) {
        for (PressureUnitsType c: PressureUnitsType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
