//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.11 at 08:37:52 PM CET 
//


package org.dexpi.xpview.model.io.xmplant;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}Equipment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Nozzle" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}PipingComponent" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}ProcessInstrument" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}InstrumentComponent" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Component" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}PipeConnectorSymbol" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}SignalConnectorSymbol" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}InsulationSymbol" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}PropertyBreak" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Label" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}PipeFlowArrow" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Units" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Date" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "equipmentOrNozzleOrPipingComponent"
})
@XmlRootElement(name = "ShapeCatalogue")
public class ShapeCatalogue {

    @XmlElements({
        @XmlElement(name = "Equipment", type = Equipment.class),
        @XmlElement(name = "Nozzle", type = Nozzle.class),
        @XmlElement(name = "PipingComponent", type = PipingComponent.class),
        @XmlElement(name = "ProcessInstrument", type = ProcessInstrument.class),
        @XmlElement(name = "InstrumentComponent", type = InstrumentComponent.class),
        @XmlElement(name = "Component", type = Component.class),
        @XmlElement(name = "PipeConnectorSymbol", type = PipeConnectorSymbol.class),
        @XmlElement(name = "SignalConnectorSymbol", type = SignalConnectorSymbol.class),
        @XmlElement(name = "InsulationSymbol", type = InsulationSymbol.class),
        @XmlElement(name = "PropertyBreak", type = PropertyBreak.class),
        @XmlElement(name = "Label", type = Label.class),
        @XmlElement(name = "PipeFlowArrow", type = PipeFlowArrow.class)
    })
    protected List<Object> equipmentOrNozzleOrPipingComponent;
    @XmlAttribute(name = "Name", required = true)
    protected java.lang.String name;
    @XmlAttribute(name = "Version")
    protected java.lang.String version;
    @XmlAttribute(name = "Units")
    protected java.lang.String units;
    @XmlAttribute(name = "Date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;

    /**
     * Gets the value of the equipmentOrNozzleOrPipingComponent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equipmentOrNozzleOrPipingComponent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEquipmentOrNozzleOrPipingComponent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Equipment }
     * {@link Nozzle }
     * {@link PipingComponent }
     * {@link ProcessInstrument }
     * {@link InstrumentComponent }
     * {@link Component }
     * {@link PipeConnectorSymbol }
     * {@link SignalConnectorSymbol }
     * {@link InsulationSymbol }
     * {@link PropertyBreak }
     * {@link Label }
     * {@link PipeFlowArrow }
     * 
     * 
     */
    public List<Object> getEquipmentOrNozzleOrPipingComponent() {
        if (equipmentOrNozzleOrPipingComponent == null) {
            equipmentOrNozzleOrPipingComponent = new ArrayList<Object>();
        }
        return this.equipmentOrNozzleOrPipingComponent;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setName(java.lang.String value) {
        this.name = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setVersion(java.lang.String value) {
        this.version = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setUnits(java.lang.String value) {
        this.units = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

}
