//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.11 at 08:37:52 PM CET 
//


package org.dexpi.xpview.model.io.xmplant;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransactionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TransactionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="to approve"/>
 *     &lt;enumeration value="to check"/>
 *     &lt;enumeration value="to copy"/>
 *     &lt;enumeration value="to create"/>
 *     &lt;enumeration value="to modify"/>
 *     &lt;enumeration value="to request"/>
 *     &lt;enumeration value="to release"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TransactionType")
@XmlEnum
public enum TransactionType {

    @XmlEnumValue("to approve")
    TO_APPROVE("to approve"),
    @XmlEnumValue("to check")
    TO_CHECK("to check"),
    @XmlEnumValue("to copy")
    TO_COPY("to copy"),
    @XmlEnumValue("to create")
    TO_CREATE("to create"),
    @XmlEnumValue("to modify")
    TO_MODIFY("to modify"),
    @XmlEnumValue("to request")
    TO_REQUEST("to request"),
    @XmlEnumValue("to release")
    TO_RELEASE("to release");
    private final java.lang.String value;

    TransactionType(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static TransactionType fromValue(java.lang.String v) {
        for (TransactionType c: TransactionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
