//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.11 at 08:37:52 PM CET 
//


package org.dexpi.xpview.model.io.xmplant;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Area" type="{}AreaUnitsType" default="SquareMetre" />
 *       &lt;attribute name="Angle" type="{}AngleUnitsType" default="Degree" />
 *       &lt;attribute name="Distance" type="{}DistanceUnitsType" default="Millimetre" />
 *       &lt;attribute name="Temperature" type="{}TemperatureUnitsType" default="DegreeCelsius" />
 *       &lt;attribute name="Pressure" type="{}PressureUnitsType" default="Bar" />
 *       &lt;attribute name="Volume" type="{}VolumeUnitsType" default="CubicMetre" />
 *       &lt;attribute name="Weight" type="{}WeightUnitsType" default="Kilogram" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "UnitsOfMeasure")
public class UnitsOfMeasure {

    @XmlAttribute(name = "Area")
    protected AreaUnitsType area;
    @XmlAttribute(name = "Angle")
    protected AngleUnitsType angle;
    @XmlAttribute(name = "Distance")
    protected DistanceUnitsType distance;
    @XmlAttribute(name = "Temperature")
    protected TemperatureUnitsType temperature;
    @XmlAttribute(name = "Pressure")
    protected PressureUnitsType pressure;
    @XmlAttribute(name = "Volume")
    protected VolumeUnitsType volume;
    @XmlAttribute(name = "Weight")
    protected WeightUnitsType weight;

    /**
     * Gets the value of the area property.
     * 
     * @return
     *     possible object is
     *     {@link AreaUnitsType }
     *     
     */
    public AreaUnitsType getArea() {
        if (area == null) {
            return AreaUnitsType.SQUARE_METRE;
        } else {
            return area;
        }
    }

    /**
     * Sets the value of the area property.
     * 
     * @param value
     *     allowed object is
     *     {@link AreaUnitsType }
     *     
     */
    public void setArea(AreaUnitsType value) {
        this.area = value;
    }

    /**
     * Gets the value of the angle property.
     * 
     * @return
     *     possible object is
     *     {@link AngleUnitsType }
     *     
     */
    public AngleUnitsType getAngle() {
        if (angle == null) {
            return AngleUnitsType.DEGREE;
        } else {
            return angle;
        }
    }

    /**
     * Sets the value of the angle property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngleUnitsType }
     *     
     */
    public void setAngle(AngleUnitsType value) {
        this.angle = value;
    }

    /**
     * Gets the value of the distance property.
     * 
     * @return
     *     possible object is
     *     {@link DistanceUnitsType }
     *     
     */
    public DistanceUnitsType getDistance() {
        if (distance == null) {
            return DistanceUnitsType.MILLIMETRE;
        } else {
            return distance;
        }
    }

    /**
     * Sets the value of the distance property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistanceUnitsType }
     *     
     */
    public void setDistance(DistanceUnitsType value) {
        this.distance = value;
    }

    /**
     * Gets the value of the temperature property.
     * 
     * @return
     *     possible object is
     *     {@link TemperatureUnitsType }
     *     
     */
    public TemperatureUnitsType getTemperature() {
        if (temperature == null) {
            return TemperatureUnitsType.DEGREE_CELSIUS;
        } else {
            return temperature;
        }
    }

    /**
     * Sets the value of the temperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemperatureUnitsType }
     *     
     */
    public void setTemperature(TemperatureUnitsType value) {
        this.temperature = value;
    }

    /**
     * Gets the value of the pressure property.
     * 
     * @return
     *     possible object is
     *     {@link PressureUnitsType }
     *     
     */
    public PressureUnitsType getPressure() {
        if (pressure == null) {
            return PressureUnitsType.BAR;
        } else {
            return pressure;
        }
    }

    /**
     * Sets the value of the pressure property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressureUnitsType }
     *     
     */
    public void setPressure(PressureUnitsType value) {
        this.pressure = value;
    }

    /**
     * Gets the value of the volume property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeUnitsType }
     *     
     */
    public VolumeUnitsType getVolume() {
        if (volume == null) {
            return VolumeUnitsType.CUBIC_METRE;
        } else {
            return volume;
        }
    }

    /**
     * Sets the value of the volume property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeUnitsType }
     *     
     */
    public void setVolume(VolumeUnitsType value) {
        this.volume = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link WeightUnitsType }
     *     
     */
    public WeightUnitsType getWeight() {
        if (weight == null) {
            return WeightUnitsType.KILOGRAM;
        } else {
            return weight;
        }
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeightUnitsType }
     *     
     */
    public void setWeight(WeightUnitsType value) {
        this.weight = value;
    }

}
