//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.11 at 08:37:52 PM CET 
//


package com.basf.xpview.model.io.xmplant;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}PlantItem">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}Discipline" minOccurs="0"/>
 *         &lt;element ref="{}MinimumDesignPressure"/>
 *         &lt;element ref="{}MaximumDesignPressure"/>
 *         &lt;element ref="{}MinimumDesignTemperature"/>
 *         &lt;element ref="{}MaximumDesignTemperature"/>
 *         &lt;element ref="{}Equipment"/>
 *         &lt;element ref="{}Nozzle"/>
 *         &lt;element ref="{}Component"/>
 *       &lt;/choice>
 *       &lt;attribute name="ProcessArea" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Purpose" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "disciplineOrMinimumDesignPressureOrMaximumDesignPressure"
})
@XmlRootElement(name = "Equipment")
public class Equipment
    extends PlantItem
{

    @XmlElementRefs({
        @XmlElementRef(name = "MaximumDesignPressure", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Nozzle", type = Nozzle.class, required = false),
        @XmlElementRef(name = "MaximumDesignTemperature", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Equipment", type = Equipment.class, required = false),
        @XmlElementRef(name = "Discipline", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "MinimumDesignTemperature", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "MinimumDesignPressure", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Component", type = Component.class, required = false)
    })
    protected List<Object> disciplineOrMinimumDesignPressureOrMaximumDesignPressure;
    @XmlAttribute(name = "ProcessArea")
    protected java.lang.String processArea;
    @XmlAttribute(name = "Purpose")
    protected java.lang.String purpose;

    /**
     * Gets the value of the disciplineOrMinimumDesignPressureOrMaximumDesignPressure property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the disciplineOrMinimumDesignPressureOrMaximumDesignPressure property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisciplineOrMinimumDesignPressureOrMaximumDesignPressure().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link PressureDouble }{@code >}
     * {@link Nozzle }
     * {@link JAXBElement }{@code <}{@link TemperatureDouble }{@code >}
     * {@link Equipment }
     * {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}
     * {@link JAXBElement }{@code <}{@link TemperatureDouble }{@code >}
     * {@link JAXBElement }{@code <}{@link PressureDouble }{@code >}
     * {@link Component }
     * 
     * 
     */
    public List<Object> getDisciplineOrMinimumDesignPressureOrMaximumDesignPressure() {
        if (disciplineOrMinimumDesignPressureOrMaximumDesignPressure == null) {
            disciplineOrMinimumDesignPressureOrMaximumDesignPressure = new ArrayList<Object>();
        }
        return this.disciplineOrMinimumDesignPressureOrMaximumDesignPressure;
    }

    /**
     * Gets the value of the processArea property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getProcessArea() {
        return processArea;
    }

    /**
     * Sets the value of the processArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setProcessArea(java.lang.String value) {
        this.processArea = value;
    }

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setPurpose(java.lang.String value) {
        this.purpose = value;
    }

}
