//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.11 at 08:37:52 PM CET 
//


package com.basf.xpview.model.io.xmplant;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="OverallLength" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="FaceDiameter" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="FaceThickness" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="FlangeThickness" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="FlangeDiameter" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="OutsideDiameter" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="HubDiameter" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Parameters")
public class Parameters {

    @XmlAttribute(name = "OverallLength")
    @XmlSchemaType(name = "anySimpleType")
    protected java.lang.String overallLength;
    @XmlAttribute(name = "FaceDiameter")
    @XmlSchemaType(name = "anySimpleType")
    protected java.lang.String faceDiameter;
    @XmlAttribute(name = "FaceThickness")
    @XmlSchemaType(name = "anySimpleType")
    protected java.lang.String faceThickness;
    @XmlAttribute(name = "FlangeThickness")
    @XmlSchemaType(name = "anySimpleType")
    protected java.lang.String flangeThickness;
    @XmlAttribute(name = "FlangeDiameter")
    @XmlSchemaType(name = "anySimpleType")
    protected java.lang.String flangeDiameter;
    @XmlAttribute(name = "OutsideDiameter")
    @XmlSchemaType(name = "anySimpleType")
    protected java.lang.String outsideDiameter;
    @XmlAttribute(name = "HubDiameter")
    @XmlSchemaType(name = "anySimpleType")
    protected java.lang.String hubDiameter;

    /**
     * Gets the value of the overallLength property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getOverallLength() {
        return overallLength;
    }

    /**
     * Sets the value of the overallLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setOverallLength(java.lang.String value) {
        this.overallLength = value;
    }

    /**
     * Gets the value of the faceDiameter property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getFaceDiameter() {
        return faceDiameter;
    }

    /**
     * Sets the value of the faceDiameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setFaceDiameter(java.lang.String value) {
        this.faceDiameter = value;
    }

    /**
     * Gets the value of the faceThickness property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getFaceThickness() {
        return faceThickness;
    }

    /**
     * Sets the value of the faceThickness property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setFaceThickness(java.lang.String value) {
        this.faceThickness = value;
    }

    /**
     * Gets the value of the flangeThickness property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getFlangeThickness() {
        return flangeThickness;
    }

    /**
     * Sets the value of the flangeThickness property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setFlangeThickness(java.lang.String value) {
        this.flangeThickness = value;
    }

    /**
     * Gets the value of the flangeDiameter property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getFlangeDiameter() {
        return flangeDiameter;
    }

    /**
     * Sets the value of the flangeDiameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setFlangeDiameter(java.lang.String value) {
        this.flangeDiameter = value;
    }

    /**
     * Gets the value of the outsideDiameter property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getOutsideDiameter() {
        return outsideDiameter;
    }

    /**
     * Sets the value of the outsideDiameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setOutsideDiameter(java.lang.String value) {
        this.outsideDiameter = value;
    }

    /**
     * Gets the value of the hubDiameter property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getHubDiameter() {
        return hubDiameter;
    }

    /**
     * Sets the value of the hubDiameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setHubDiameter(java.lang.String value) {
        this.hubDiameter = value;
    }

}
