//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.11 at 08:37:52 PM CET 
//


package com.basf.xpview.model.io.xmplant;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}Curve">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{}Circle"/>
 *           &lt;element ref="{}Ellipse"/>
 *         &lt;/choice>
 *         &lt;element ref="{}GenericAttributes" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="StartAngle" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="EndAngle" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "circle",
    "ellipse",
    "genericAttributes"
})
public class TrimmedCurve
    extends Curve
{

    @XmlElement(name = "Circle")
    protected Circle circle;
    @XmlElement(name = "Ellipse")
    protected Ellipse ellipse;
    @XmlElement(name = "GenericAttributes")
    protected GenericAttributes genericAttributes;
    @XmlAttribute(name = "StartAngle", required = true)
    protected double startAngle;
    @XmlAttribute(name = "EndAngle", required = true)
    protected double endAngle;

    /**
     * Gets the value of the circle property.
     * 
     * @return
     *     possible object is
     *     {@link Circle }
     *     
     */
    public Circle getCircle() {
        return circle;
    }

    /**
     * Sets the value of the circle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Circle }
     *     
     */
    public void setCircle(Circle value) {
        this.circle = value;
    }

    /**
     * Gets the value of the ellipse property.
     * 
     * @return
     *     possible object is
     *     {@link Ellipse }
     *     
     */
    public Ellipse getEllipse() {
        return ellipse;
    }

    /**
     * Sets the value of the ellipse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ellipse }
     *     
     */
    public void setEllipse(Ellipse value) {
        this.ellipse = value;
    }

    /**
     * Gets the value of the genericAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link GenericAttributes }
     *     
     */
    public GenericAttributes getGenericAttributes() {
        return genericAttributes;
    }

    /**
     * Sets the value of the genericAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericAttributes }
     *     
     */
    public void setGenericAttributes(GenericAttributes value) {
        this.genericAttributes = value;
    }

    /**
     * Gets the value of the startAngle property.
     * 
     */
    public double getStartAngle() {
        return startAngle;
    }

    /**
     * Sets the value of the startAngle property.
     * 
     */
    public void setStartAngle(double value) {
        this.startAngle = value;
    }

    /**
     * Gets the value of the endAngle property.
     * 
     */
    public double getEndAngle() {
        return endAngle;
    }

    /**
     * Sets the value of the endAngle property.
     * 
     */
    public void setEndAngle(double value) {
        this.endAngle = value;
    }

}
