//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.11 at 08:37:52 PM CET 
//


package com.basf.xpview.model.io.xmplant;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WeightUnitsType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="WeightUnitsType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="mg"/>
 *     &lt;enumeration value="Kg"/>
 *     &lt;enumeration value="lb"/>
 *     &lt;enumeration value="oz"/>
 *     &lt;enumeration value="Microgram"/>
 *     &lt;enumeration value="Milligram"/>
 *     &lt;enumeration value="Gram"/>
 *     &lt;enumeration value="Kilogram"/>
 *     &lt;enumeration value="Megagram"/>
 *     &lt;enumeration value="PoundMass"/>
 *     &lt;enumeration value="OunceMass"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "WeightUnitsType")
@XmlEnum
public enum WeightUnitsType {

    @XmlEnumValue("mg")
    MG("mg"),
    @XmlEnumValue("Kg")
    KG("Kg"),
    @XmlEnumValue("lb")
    LB("lb"),
    @XmlEnumValue("oz")
    OZ("oz"),
    @XmlEnumValue("Microgram")
    MICROGRAM("Microgram"),
    @XmlEnumValue("Milligram")
    MILLIGRAM("Milligram"),
    @XmlEnumValue("Gram")
    GRAM("Gram"),
    @XmlEnumValue("Kilogram")
    KILOGRAM("Kilogram"),
    @XmlEnumValue("Megagram")
    MEGAGRAM("Megagram"),
    @XmlEnumValue("PoundMass")
    POUND_MASS("PoundMass"),
    @XmlEnumValue("OunceMass")
    OUNCE_MASS("OunceMass");
    private final java.lang.String value;

    WeightUnitsType(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static WeightUnitsType fromValue(java.lang.String v) {
        for (WeightUnitsType c: WeightUnitsType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
