package com.basf.xpview.model.io;

public enum ImportHints {
	KEY_EQUIPMENT_POSITION,
	VALUE_EQUIPMENT_POSITION_ENABLED,
	VALUE_EQUIPMENT_POSITION_DISABLED,
	
	KEY_SO_FLAT_EQUIPMENT,
	VALUE_SO_FLAT_EQUIPMENT_DISABLED,
	VALUE_SO_FLAT_EQUIPMENT_ENABLED,
}
